-- Step 2: Add missing columns to incidents table
-- Run this after step 1

ALTER TABLE incidents 
ADD COLUMN IF NOT EXISTS scanned_images text[],
ADD COLUMN IF NOT EXISTS incident_number text,
ADD COLUMN IF NOT EXISTS list_number text,
ADD COLUMN IF NOT EXISTS arrival_time time,
ADD COLUMN IF NOT EXISTS return_time time,
ADD COLUMN IF NOT EXISTS retired_time time,
ADD COLUMN IF NOT EXISTS company_number text,
ADD COLUMN IF NOT EXISTS department text,
ADD COLUMN IF NOT EXISTS floor text,
ADD COLUMN IF NOT EXISTS commune text,
ADD COLUMN IF NOT EXISTS population text,
ADD COLUMN IF NOT EXISTS fire_rescue_location text,
ADD COLUMN IF NOT EXISTS damage text,
ADD COLUMN IF NOT EXISTS has_insurance boolean,
ADD COLUMN IF NOT EXISTS insurance_company text,
ADD COLUMN IF NOT EXISTS mobile_units text[],
ADD COLUMN IF NOT EXISTS insurance_conductors text,
ADD COLUMN IF NOT EXISTS other_classes text,
ADD COLUMN IF NOT EXISTS company_quinta int,
ADD COLUMN IF NOT EXISTS company_primera int,
ADD COLUMN IF NOT EXISTS company_segunda int,
ADD COLUMN IF NOT EXISTS company_tercera int,
ADD COLUMN IF NOT EXISTS company_cuarta int,
ADD COLUMN IF NOT EXISTS company_sexta int,
ADD COLUMN IF NOT EXISTS company_septima int,
ADD COLUMN IF NOT EXISTS company_octava int,
ADD COLUMN IF NOT EXISTS company_bc_bp int,
ADD COLUMN IF NOT EXISTS attendance_correction text,
ADD COLUMN IF NOT EXISTS sector_rural boolean,
ADD COLUMN IF NOT EXISTS sector_location text,
ADD COLUMN IF NOT EXISTS sector_numbers int[],
ADD COLUMN IF NOT EXISTS cant_lesionados int,
ADD COLUMN IF NOT EXISTS cant_involucrados int,
ADD COLUMN IF NOT EXISTS cant_damnificados int,
ADD COLUMN IF NOT EXISTS cant_7_3 int,
ADD COLUMN IF NOT EXISTS report_prepared_by text,
ADD COLUMN IF NOT EXISTS list_prepared_by text,
ADD COLUMN IF NOT EXISTS officer_in_charge text,
ADD COLUMN IF NOT EXISTS called_by_command text;
